<?xml version='1.0' encoding='UTF-8'?>
<result plugin="junit@1.18">
  <suites>
    <suite>
      <file>/var/lib/jenkins/jobs/Integration Tests/workspace/report/integration-reports.xml</file>
      <name>Mocha Tests</name>
      <duration>3.153</duration>
      <timestamp>Thu, 18 Aug 2016 03:33:19 GMT</timestamp>
      <time>3.153</time>
      <cases>
        <case>
          <duration>2.005</duration>
          <className>Integration Testing for http://crud-node-6-node6-restful.apps.10.2.2.2.xip.io</className>
          <testName>post object</testName>
          <skipped>false</skipped>
          <errorStackTrace>timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.</errorStackTrace>
          <failedSince>12</failedSince>
        </case>
        <case>
          <duration>0.0</duration>
          <className>Integration Testing for http://crud-node-6-node6-restful.apps.10.2.2.2.xip.io</className>
          <testName>retrieves an object</testName>
          <skipped>false</skipped>
          <errorStackTrace>Cannot read property &apos;_id&apos; of null
TypeError: Cannot read property &apos;_id&apos; of null
    at test/integration/integration.js:34:33
    at Request.callback (node_modules/superagent/lib/node/index.js:591:12)
    at node_modules/superagent/lib/node/index.js:767:18
    at IncomingMessage.&lt;anonymous&gt; (node_modules/superagent/lib/node/parsers/json.js:16:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)</errorStackTrace>
          <failedSince>12</failedSince>
        </case>
        <case>
          <duration>0.0</duration>
          <className>Integration Testing for http://crud-node-6-node6-restful.apps.10.2.2.2.xip.io</className>
          <testName>retrieves a collection</testName>
          <skipped>false</skipped>
          <errorStackTrace>expected [ Array(5) ] to include undefined
AssertionError: expected [ Array(5) ] to include undefined
    at test/integration/integration.js:47:66
    at Request.callback (node_modules/superagent/lib/node/index.js:591:12)
    at node_modules/superagent/lib/node/index.js:767:18
    at IncomingMessage.&lt;anonymous&gt; (node_modules/superagent/lib/node/parsers/json.js:16:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)</errorStackTrace>
          <failedSince>12</failedSince>
        </case>
      </cases>
    </suite>
  </suites>
  <duration>3.153</duration>
  <keepLongStdio>false</keepLongStdio>
</result>